### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by c0001** [xyqyear/create_m3u_from_NeteaseCloudMusic#1]
你好同学：

默认安装的网易云， dat文件位置为系统默认。

python 版本 3.5.4

操作系统平台： win10

错误信息：
```
Traceback (most recent call last):
  File "a:/20171229171252/elements/git-repo/create_m3u_from_NeteaseCloudMusic/Exporter.py", line 207, in <module>
    songs = tid2dir_offline(library_dat, webdb_dat)
  File "a:/20171229171252/elements/git-repo/create_m3u_from_NeteaseCloudMusic/Exporter.py", line 103, in tid2dir_offline
    tid = int(tid)
ValueError: invalid literal for int() with base 10: '49b772fcaec54b4250c9b9aad0005892'
```

exe 编译文件同样无法使用闪退，调用命令行调试结果同上，并提示找不到数据库。

**Comment by c0001** [comment]
是不是一定要安装sqlite py文件才能运行， 是不是把sqlite command tool 编译进了exe?

**Comment by xyqyear** [comment]
知道问题在哪儿了，但是不确定解决了之后会不会出问题，代码是[更改](https://github.com/xyqyear/create_m3u_from_NeteaseCloudMusic/commit/38ac3fa83be76e85939f5184f4ed5b442ad4a0bc)了，如果方便的话能不能把数据库文件上传上来我看看？路径是 C:/Users/你的用户名/AppData/Local/Netease/CloudMusic/Library/webdb.dat
